# AWS Glue PySpark ETL — dim_employees
# Table Role: dimension
# Generated by DataAutomation

import sys
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job
from pyspark.sql.functions import col, current_timestamp

args = getResolvedOptions(sys.argv, ['JOB_NAME', 'SOURCE_JDBC_URL', 'SOURCE_USER',
                                      'SOURCE_PASSWORD', 'TARGET_S3_PATH', 'TARGET_DB'])
sc          = SparkContext()
glueContext = GlueContext(sc)
spark       = glueContext.spark_session
job         = Job(glueContext)
job.init(args['JOB_NAME'], args)

# ── Extract ──────────────────────────────────────────────────────
src_df = spark.read \
    .format("jdbc") \
    .option("url", args["SOURCE_JDBC_URL"]) \
    .option("dbtable", "dbo.Employees") \
    .option("user", args["SOURCE_USER"]) \
    .option("password", args["SOURCE_PASSWORD"]) \
    .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver") \
    .load()

print(f"Extracted {src_df.count()} rows from dbo.Employees")

# ── Transform ─────────────────────────────────────────────────────
tgt_df = src_df.select(
    col('FirstName').alias('firstname'), col('LastName').alias('lastname'), col('Email').alias('email'), col('Department').alias('department'), col('HireDate').alias('hiredate'), col('ManagerID').alias('managerid'), col('IsActive').alias('isactive'),
    current_timestamp().alias("dw_load_ts"),
)

# ── Load ──────────────────────────────────────────────────────────
output_path = f"{args['TARGET_S3_PATH']}/dw/dim_employees"

tgt_df.write \
    .mode("overwrite") \
    .format("parquet") \
    .option("path", output_path) \
    .saveAsTable(f"{args['TARGET_DB']}.dw_dim_employees")

print(f"Loaded {tgt_df.count()} rows to {output_path}")

job.commit()
