    """
    Dimension Load Script — dw.dim_regions
    Generated by DataAutomation
    Source : dbo.Regions
    Target : dw.dim_regions
    Strategy: SCD Type 1 (upsert)
    """

    import os
    import json
    import datetime
    import pyodbc  # target is always the DW (PostgreSQL via psycopg2 in prod, pyodbc for SQL DW)

    # ── Configuration (injected at runtime via environment) ───────────────
    SOURCE_HOST     = os.environ["SOURCE_HOST"]
    SOURCE_PORT     = int(os.environ.get("SOURCE_PORT", "1433"))
    SOURCE_DATABASE = os.environ["SOURCE_DATABASE"]
    SOURCE_USERNAME = os.environ["SOURCE_USERNAME"]
    SOURCE_PASSWORD = os.environ["SOURCE_PASSWORD"]

    TARGET_HOST     = os.environ["TARGET_HOST"]
    TARGET_PORT     = int(os.environ.get("TARGET_PORT", "5432"))
    TARGET_DATABASE = os.environ["TARGET_DATABASE"]
    TARGET_USERNAME = os.environ["TARGET_USERNAME"]
    TARGET_PASSWORD = os.environ["TARGET_PASSWORD"]
    TARGET_SCHEMA   = os.environ.get("TARGET_SCHEMA", "dw")

    # ── Logger ────────────────────────────────────────────────────────────
    def log(level: str, message: str, **kwargs):
        print(json.dumps({
            "ts": datetime.datetime.utcnow().isoformat(),
            "level": level,
            "script": "dim_regions",
            "message": message,
            **kwargs,
        }))

    # ── Main ──────────────────────────────────────────────────────────────
    def run():
        log("info", "Starting dimension load", target="dw.dim_regions")

        # Source connection
        import pyodbc
src_conn = pyodbc.connect(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    f"SERVER={SOURCE_HOST},{SOURCE_PORT};"
    f"DATABASE={SOURCE_DATABASE};"
    f"UID={SOURCE_USERNAME};"
    f"PWD={SOURCE_PASSWORD};"
    "Encrypt=yes;TrustServerCertificate=yes;Connection Timeout=30;"
)
src_cursor = src_conn.cursor()

        # Target connection (PostgreSQL)
        import psycopg2
        tgt_conn = psycopg2.connect(
            host=TARGET_HOST, port=TARGET_PORT, dbname=TARGET_DATABASE,
            user=TARGET_USERNAME, password=TARGET_PASSWORD,
        )
        tgt_cursor = tgt_conn.cursor()

        # ── Extract ───────────────────────────────────────────────────────
        log("info", "Extracting from source", source="dbo.Regions")
        src_cursor.execute(
            """
            SELECT
                RegionID,
    RegionName,
    SalesTarget
            FROM dbo.Regions
            """
        )
        rows = src_cursor.fetchall()
        log("info", f"Extracted {len(rows)} rows")

        # ── Load (SCD Type 1 Upsert) ──────────────────────────────────────
        rows_inserted = 0
        rows_updated  = 0

        for row in rows:
            # Check existence by natural key
            tgt_cursor.execute(
                "SELECT 1 FROM {TARGET_SCHEMA}.dim_regions WHERE ",
                (,),
            )
            exists = tgt_cursor.fetchone()

            if exists is None:
                tgt_cursor.execute(
                    f"INSERT INTO {TARGET_SCHEMA}.dim_regions (regionname, salestarget) "
                    f"VALUES (?, ?)",
                    (row.RegionName, row.SalesTarget,),
                )
                rows_inserted += 1
            else:
                tgt_cursor.execute(
                    f"""UPDATE {TARGET_SCHEMA}.dim_regions
                           SET regionname = ?,
        salestarget = ?
                         WHERE """,
                    (row.RegionName, row.SalesTarget, ,),
                )
                rows_updated += 1

        tgt_conn.commit()
        log("info", "Load complete",
            rows_inserted=rows_inserted,
            rows_updated=rows_updated)

        src_cursor.close(); src_conn.close()
        tgt_cursor.close(); tgt_conn.close()


    if __name__ == "__main__":
        run()
