-- === SNAPSHOT (place in snapshots/) ===
        {% snapshot dim_customers_snapshot %}

        {{
            config(
                target_schema='dw',
                unique_key='CustomerID',
                strategy='check',
                check_cols='all',
            )
        }}

        select
            {{ dbt_utils.surrogate_key(['CustomerID']) }} as customers_sk,
            FirstName as firstname,
LastName as lastname,
Email as email,
Phone as phone,
Country as country,
CreatedAt as createdat,
IsActive as isactive,
            current_timestamp() as dw_load_ts
        from {{ source('dbo', 'Customers') }}

        {% endsnapshot %}


-- === MODEL (place in models/) ===
-- dbt model: dim_customers
-- Role: Dimension (SCD Type 2 via snapshot)
-- Generated by DataAutomation

{{
    config(
        materialized='table',
        schema='dw',
    )
}}

select *
from {{ ref('dim_customers_snapshot') }}
where dbt_valid_to is null  -- current records only
